config/routes.rb
Rails.application.routes.draw do




  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope module: :api do
    scope module: :v1 do
      resources :orders, :defaults => { :format => 'json' }, :only => [:index,:show] do
        post "" ,action: :direction
      end
      resources :notice, :defaults => { :format => 'json' }, :only => [:index]
      resource :users, :defaults => { :format => 'json' }, :only => [:update] do
        post :login
      end
    end
  end
  devise_for :staffs, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  scope module: :staffs do
    resources :staff
  end

  root 'site#home'

  resources :task_job_links
  resources :vacations
  resources :divisions do
    collection do
      put :update_tree
    end
  end
  resources :facilities
  resources :calendar , :only => [:index]
  resources :companies
  resources :media_assets
  resources :task_performs
  resources :tasks
  resources :professions
  resources :contract_types
  resources :workers
  resources :year_shedules
  resources :consumables
  resources :job_links
  resources :appliances
  resources :inventories
  resources :jobs
  resources :job_types
  resources :job_units
  resources :notifications
  resources :work_time_limits
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/appliance.rb
class Appliance < ApplicationRecord
  has_many :job_links, as: :jobable , dependent: :destroy
  has_many :jobs, through: :job_links
  validates_presence_of :name
end

app/models/company.rb
class Company < ApplicationRecord
  validates_presence_of :name
  has_many :divisions , as: :parent

  
end

app/models/consumable.rb
class Consumable < ApplicationRecord
  has_many :job_links, as: :jobable , dependent: :destroy
  has_many :jobs, through: :job_links
  validates_presence_of :name
end

app/models/division.rb
class Division < ApplicationRecord
  validates_presence_of  :name
  belongs_to :parent, polymorphic: true, optional: true
  has_many :divisions , as: :parent
  has_many :facilities

end

app/models/facility.rb
class Facility < ApplicationRecord
  belongs_to :division
  validates_presence_of :name
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  has_many :job_links, as: :jobable , dependent: :destroy
  has_many :jobs, through: :job_links
  validates_presence_of :name
end

app/models/job.rb
class Job < ApplicationRecord
  validates_presence_of :name ,:work_time , :number , :units
  WORK_TIME = ["да" , "нет" , "обед"]
  has_many :tasks
  has_many :job_links
  def inventories
    job_links.where(:jobable_type => "Inventory").map{|a| a.jobable}
  end
  def appliances
    job_links.where(:jobable_type => "Appliance").map{|a| a.jobable}
  end
  def consumables
    job_links.where(:jobable_type => "Consumable").map{|a| a.jobable}
  end

end

app/models/job_link.rb
class JobLink < ApplicationRecord
  belongs_to :job
  belongs_to :jobable, polymorphic: true
  validates_presence_of :job, :jobable
  validate :check_uniqness
  def check_uniqness
    self.errors.add(:job_link, "already exist") if self.class.where(:job_id => self.job_id).where(:jobable_type => self.jobable_type).where(:jobable_id=> self.jobable_id).present?
  end

end

app/models/job_type.rb
class JobType < ApplicationRecord
  has_many :jobs
end

app/models/job_unit.rb
class JobUnit < ApplicationRecord
  has_many :jobs
end

app/models/media_asset.rb
class MediaAsset < ApplicationRecord
    validates_presence_of :mediaable_id ,:mediaable_type
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notificable, polymorphic: true, required: false
  belongs_to :task
  belongs_to :staff
  validates_presence_of :title, :body
  attr_accessor :kind

end

app/models/profession.rb
class Profession < ApplicationRecord
  validates_presence_of :name
  has_many :workers
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_fclay_attachment
  has_many :notifications
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :job_links
  belongs_to :facility
  belongs_to :job
  belongs_to :worker, optional: true
  has_one :task_perform
  has_many :notifications
  validates_presence_of :name , :number
  attr_accessor :status
  attr_accessor :night_hours
  attr_accessor :control
  attr_accessor :begin_at_date
  attr_accessor :begin_at_time
  attr_accessor :finish_at_date
  attr_accessor :finish_at_time
  COMPLEXITY = %w(1 2 3)
  validate :date_validation
  before_create :fetch_perfrom_conditions
  before_validation :set_begin_at
  before_validation :set_finish_at


  def set_begin_at
    date = @begin_at_date+" "+@begin_at_time if @begin_at_date && @begin_at_time
    self.begin_at = DateTime.parse(date) if @begin_at_date && @begin_at_time
  end

  def set_finish_at
    date = @finish_at_date+" "+@finish_at_time  if @finish_at_date && @finish_at_time
    self.finish_at = DateTime.parse(date) if @finish_at_date && @finish_at_time
  end

  def date_validation
    if self.finish_at.to_i < self.begin_at.to_i
      errors.add :finish_at, "cannot be less than start date "
    end
  end

  def status
    return "free" unless self.worker.present?
    return "sheduled" unless self.task_perform.present?
    case self.task_perform.status
      when "pending"
        "inprogress"
      when "successful"
        "completed"
      else
        "unknown"
    end
  end

  def fetch_status
    return unless task_perform.present?
    task_perform.fetch_status
  end

  def fetch_perfrom_conditions
    self.perform_conditions = @control.join(",") if @control
  end

end

app/models/vacation.rb
class Vacation < ApplicationRecord
  belongs_to :worker
  validates_presence_of :worker_id
end

app/models/worker.rb
class Worker < ApplicationRecord
  belongs_to :contract_type
  belongs_to :profession
  belongs_to :work_time_limit
  validates_presence_of :name , :surname , :middle_name
  before_create :generate_qr_code
  TIME_TRACK = ["В пределах плана", "По плану" , "По факту"]


  def generate_qr_code
    self.qr_code = SecureRandom.hex 15
  end
end

app/controllers/companies_controller.rb
class CompaniesController < InheritedResources::Base
  skip_before_action :verify_authenticity_token
  before_action :authenticate_staff!
  before_action :set_additional, :only => :show

  layout "bootkit"


  def reorder

  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end

  private

    def set_additional
      @additional_js = %w(bootkit/jquery.nestable bootkit/init-nestable bootkit/update_tree)
      @additional_css = %w(bootkit/jquery.nestable)
    end

    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/api_helper.rb
module ApiHelper
  
  def fetch_actual_date 
    
    lasts_updated_at = []
    
    [Level, Lesson, LessonPart, Verb, Sentence].each do |f|
      lasts_updated_at.push f.maximum(:updated_at)
    end
    
    lasts_updated_at.compact!
    
    lasts_updated_at.size == 0 ? Time.now : lasts_updated_at.max
    
  end
  
  def generate_token size=25
      raw = SecureRandom.hex size
      md5 = Digest::MD5.hexdigest(raw)
      {:raw => raw, :md5 => md5}
  end
  
  def md5 raw
     Digest::MD5.hexdigest(raw)
  end
  
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/companies/_form.html.haml
.row
  .col-md-8.col-md-offset-2
    %form{:role => "form"}
    = form_with(model: company, local: true) do |form|
      - if company.errors.any?
        #error_explanation
          %h2
            = pluralize(company.errors.count, "error")
            prohibited this company from being saved:
          %ul
            - company.errors.full_messages.each do |message|
              %li= message  
      .form-group
        %label{:for => "exampleInputEmail1"} Название
        = form.text_field :name, id: :company_name, :class => "form-control"
      
      %br
      = form.submit "Сохранить", :class => "btn btn-primary"

app/views/companies/edit.html.haml
.row
  .col-sm-12
    %section.panel
      %header.panel-heading
        Редактирование организации
        %span.tools.pull-right
          = link_to 'Назад', @company , :class => "btn btn-danger btn-xs header-button"
      .panel-body
        = render 'form', company: @company

app/views/companies/index.html.haml
.row
  .col-sm-12
    %section.panel
      %header.panel-heading
        Организации
        %span.tools.pull-right
          = link_to 'Создать', new_company_path, :class => "btn btn-primary btn-xs header-button"
      .panel-body
        %table.table.table-hover.general-table
          %thead
            %tr
              %th  #
              %th Название
          %tbody
          - @companies.each do |company|
            %tr
              %td= company.id
              %td= company.name
              %td
                = link_to 'Подробнее', company, :class => "btn btn-info btn-xs"

app/views/companies/new.html.haml
.row
  .col-sm-12
    %section.panel
      %header.panel-heading
        Создание организации
        %span.tools.pull-right
          = link_to 'Назад', companies_path , :class => "btn btn-danger btn-xs header-button"
      .panel-body
        = render 'form', company: @company

app/views/companies/show.html.haml
.row
  .col-sm-6
    %section.panel
      %header.panel-heading
        %span.tools.pull-right
          = link_to 'Назад', companies_path , :class => "btn btn-danger btn-xs header-button"
        %h3= @company.name
      .panel-body
        %br
        %table.table
          %tr
            %td ИНН
            %td 234234234
          %tr
            %td КПП
            %td 56756756756
        %br
        =  button_to 'Изменить', edit_company_path(@company) , method: :get, :class => "btn btn-success btn-block"

        = button_to 'Удалить', @company, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-block"
        %br




  .col-sm-6
    %section.panel
      .col-lg-12
      .row
        =form_tag("/divisions/update_tree" ,method: :put)  do
          =text_field_tag "tree_data",nil, :id => "nestable_list_1_output", :style =>"display:none"
          =text_field_tag "parent",@company.id, :style =>"display:none"
          = submit_tag 'Сохранить', :id => "hide_save_tree", :style =>"display:none"
      %header.panel-heading
        %span.tools.pull-right
        = link_to 'Создать', new_division_path(:parent_id => @company.id ,:parent_type => @company.class), :class => "btn btn-primary btn-xs header-button"
        = link_to 'Сохранить',nil, :class => " btn-xs btn btn-info", :id => "save_tree_buttom"
        %h3 Подразделения

        = render :partial => 'divisions/division'