config/routes.rb
Rails.application.routes.draw do




  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope module: :api do
    scope module: :v1 do
      resources :orders, :defaults => { :format => 'json' }, :only => [:index,:show] do
        post "" ,action: :direction
      end
      resources :notice, :defaults => { :format => 'json' }, :only => [:index]
      resource :users, :defaults => { :format => 'json' }, :only => [:update] do
        post :login
      end
    end
  end
  devise_for :staffs, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  scope module: :staffs do
    resources :staff
  end

  root 'site#home'

  resources :task_job_links
  resources :vacations
  resources :divisions do
    collection do
      put :update_tree
    end
  end
  resources :facilities
  resources :calendar , :only => [:index]
  resources :companies
  resources :media_assets
  resources :task_performs
  resources :tasks
  resources :professions
  resources :contract_types
  resources :workers
  resources :year_shedules
  resources :consumables
  resources :job_links
  resources :appliances
  resources :inventories
  resources :jobs
  resources :job_types
  resources :job_units
  resources :notifications
  resources :work_time_limits
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/appliance.rb
class Appliance < ApplicationRecord
  has_many :job_links, as: :jobable , dependent: :destroy
  has_many :jobs, through: :job_links
  validates_presence_of :name
end

app/models/company.rb
class Company < ApplicationRecord
  validates_presence_of :name
  has_many :divisions , as: :parent

  
end

app/models/consumable.rb
class Consumable < ApplicationRecord
  has_many :job_links, as: :jobable , dependent: :destroy
  has_many :jobs, through: :job_links
  validates_presence_of :name
end

app/models/division.rb
class Division < ApplicationRecord
  validates_presence_of  :name
  belongs_to :parent, polymorphic: true, optional: true
  has_many :divisions , as: :parent
  has_many :facilities

end

app/models/facility.rb
class Facility < ApplicationRecord
  belongs_to :division
  validates_presence_of :name
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  has_many :job_links, as: :jobable , dependent: :destroy
  has_many :jobs, through: :job_links
  validates_presence_of :name
end

app/models/job.rb
class Job < ApplicationRecord
  validates_presence_of :name ,:work_time , :number , :units
  WORK_TIME = ["да" , "нет" , "обед"]
  has_many :tasks
  has_many :job_links
  def inventories
    job_links.where(:jobable_type => "Inventory").map{|a| a.jobable}
  end
  def appliances
    job_links.where(:jobable_type => "Appliance").map{|a| a.jobable}
  end
  def consumables
    job_links.where(:jobable_type => "Consumable").map{|a| a.jobable}
  end

end

app/models/job_link.rb
class JobLink < ApplicationRecord
  belongs_to :job
  belongs_to :jobable, polymorphic: true
  validates_presence_of :job, :jobable
  validate :check_uniqness
  def check_uniqness
    self.errors.add(:job_link, "already exist") if self.class.where(:job_id => self.job_id).where(:jobable_type => self.jobable_type).where(:jobable_id=> self.jobable_id).present?
  end

end

app/models/job_type.rb
class JobType < ApplicationRecord
  has_many :jobs
end

app/models/job_unit.rb
class JobUnit < ApplicationRecord
  has_many :jobs
end

app/models/media_asset.rb
class MediaAsset < ApplicationRecord
    validates_presence_of :mediaable_id ,:mediaable_type
end

app/models/profession.rb
class Profession < ApplicationRecord
  validates_presence_of :name
  has_many :workers
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_fclay_attachment
  has_many :notifications
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :job_links
  belongs_to :facility
  belongs_to :job
  belongs_to :worker, optional: true
  has_one :task_perform
  has_many :notifications
  validates_presence_of :name , :number
  attr_accessor :status
  attr_accessor :night_hours
  attr_accessor :control
  attr_accessor :begin_at_date
  attr_accessor :begin_at_time
  attr_accessor :finish_at_date
  attr_accessor :finish_at_time
  COMPLEXITY = %w(1 2 3)
  validate :date_validation
  before_create :fetch_perfrom_conditions
  before_validation :set_begin_at
  before_validation :set_finish_at


  def set_begin_at
    date = @begin_at_date+" "+@begin_at_time if @begin_at_date && @begin_at_time
    self.begin_at = DateTime.parse(date) if @begin_at_date && @begin_at_time
  end

  def set_finish_at
    date = @finish_at_date+" "+@finish_at_time  if @finish_at_date && @finish_at_time
    self.finish_at = DateTime.parse(date) if @finish_at_date && @finish_at_time
  end

  def date_validation
    if self.finish_at.to_i < self.begin_at.to_i
      errors.add :finish_at, "cannot be less than start date "
    end
  end

  def status
    return "free" unless self.worker.present?
    return "sheduled" unless self.task_perform.present?
    case self.task_perform.status
      when "pending"
        "inprogress"
      when "successful"
        "completed"
      else
        "unknown"
    end
  end

  def fetch_status
    return unless task_perform.present?
    task_perform.fetch_status
  end

  def fetch_perfrom_conditions
    self.perform_conditions = @control.join(",") if @control
  end

end

app/models/vacation.rb
class Vacation < ApplicationRecord
  belongs_to :worker
  validates_presence_of :worker_id
end

app/models/worker.rb
class Worker < ApplicationRecord
  belongs_to :contract_type
  belongs_to :profession
  belongs_to :work_time_limit
  validates_presence_of :name , :surname , :middle_name
  before_create :generate_qr_code
  TIME_TRACK = ["В пределах плана", "По плану" , "По факту"]


  def generate_qr_code
    self.qr_code = SecureRandom.hex 15
  end
end

app/models/year_shedule.rb
class YearShedule < ApplicationRecord
  validates_presence_of :year ,:name

end

app/controllers/year_shedules_controller.rb
class YearShedulesController < InheritedResources::Base
  skip_before_action :verify_authenticity_token
  before_action :authenticate_staff!
  layout "bootkit"
  private

    def year_shedule_params
      params.require(:year_shedule).permit(:year, :name)
    end
end

app/helpers/api_helper.rb
module ApiHelper
  
  def fetch_actual_date 
    
    lasts_updated_at = []
    
    [Level, Lesson, LessonPart, Verb, Sentence].each do |f|
      lasts_updated_at.push f.maximum(:updated_at)
    end
    
    lasts_updated_at.compact!
    
    lasts_updated_at.size == 0 ? Time.now : lasts_updated_at.max
    
  end
  
  def generate_token size=25
      raw = SecureRandom.hex size
      md5 = Digest::MD5.hexdigest(raw)
      {:raw => raw, :md5 => md5}
  end
  
  def md5 raw
     Digest::MD5.hexdigest(raw)
  end
  
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/year_shedules_helper.rb
module YearShedulesHelper
end

app/views/year_shedules/_form.html.haml
.row
  .col-md-8.col-md-offset-2
    %form{:role => "form"}
    = form_with(model: year_shedule, local: true) do |form|
      - if year_shedule.errors.any?
        #error_explanation
          %h2
            = pluralize(year_shedule.errors.count, "error")
            prohibited this year_shedule from being saved:
          %ul
            - year_shedule.errors.full_messages.each do |message|
              %li= message
      .form-group
        %label{:for => "exampleInputEmail1"} Название
        = form.text_field :name, id: :year_shedule_name, :class => "form-control"
      .form-group
        %label{:for => "exampleInputEmail1"} Год
        = form.select :year, %w(2017 2018 2019 2020) , :class => "form-control"


      %br
      = form.submit "Сохранить", :class => "btn btn-primary"

app/views/year_shedules/edit.html.haml
.row
  .col-sm-12
    %section.panel
      %header.panel-heading
        Редактирование годового графика
        %span.tools.pull-right
          = link_to 'Назад', year_shedule_path , :class => "btn btn-danger btn-xs header-button"
      .panel-body
        = render 'form', year_shedule: @year_shedule

app/views/year_shedules/index.html.haml
.row
  .col-sm-12
    %section.panel
      %header.panel-heading
        Годовой график
        %span.tools.pull-right
          = link_to 'Создать', new_year_shedule_path, :class => "btn btn-primary btn-xs header-button"
      .panel-body
        %table.table.table-hover.general-table
          %thead
            %tr
              %th #
              %th Название
              %th Год
              %th Дата
          %tbody
          - @year_shedules.each do |year_shedule|
            %tr
              %td= year_shedule.id
              %td= year_shedule.name
              %td= year_shedule.year
              %td= year_shedule.data
              %td
                = link_to 'Подробнее', year_shedule, :class => "btn btn-info btn-xs"

app/views/year_shedules/new.html.haml
.row
  .col-sm-12
    %section.panel
      %header.panel-heading
        Создание годового графика
        %span.tools.pull-right
          = link_to 'Назад', year_shedules_path , :class => "btn btn-danger btn-xs header-button"
      .panel-body
        = render 'form', year_shedule: @year_shedule

app/views/year_shedules/show.html.haml
.row
  .col-sm-6
    %section.panel
      %header.panel-heading
        %span.tools.pull-right
          = link_to 'Назад', year_shedules_path , :class => "btn btn-danger btn-xs header-button"
        %h3= @year_shedule.name
      .panel-body
        %br
        %table.table
          %tr
            %td Год
            %td=@year_shedule.year

        %br
        = button_to 'Изменить',edit_year_shedule_path(@year_shedule) , method: :get, :class => "btn btn-success btn-block"

        = button_to 'Удалить', @year_shedule, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-block"